name: Publish Qlever Petrimaps

on:
    push: 
        branches: ["master"]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v5.5.1
          with:
            images: makingsenseinfo/qlever-petrimaps
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to DockerHub
          if: github.event_name != 'pull_request'
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: |
                ${{ steps.docker_meta.outputs.tags }}
                ${{ github.ref == 'refs/heads/master' && 'makingsenseinfo/qlever-petrimaps:latest' || '' }}
            labels: ${{ steps.docker_meta.outputs.labels }}
            platforms: |
                linux/amd64
                linux/arm64
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}